/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// エンコード追加成功応答データ
    /// </summary>
    [DataContract(Name = "AddedEncode")]
    public partial class AddedEncode : IEquatable<AddedEncode>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddedEncode" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddedEncode() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddedEncode" /> class.
        /// </summary>
        /// <param name="encodeId">エンコード id (required).</param>
        public AddedEncode(int encodeId = default(int))
        {
            this.EncodeId = encodeId;
        }

        /// <summary>
        /// エンコード id
        /// </summary>
        /// <value>エンコード id</value>
        [DataMember(Name = "encodeId", IsRequired = true, EmitDefaultValue = false)]
        public int EncodeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddedEncode {\n");
            sb.Append("  EncodeId: ").Append(EncodeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddedEncode);
        }

        /// <summary>
        /// Returns true if AddedEncode instances are equal
        /// </summary>
        /// <param name="input">Instance of AddedEncode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddedEncode input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.EncodeId == input.EncodeId ||
                    this.EncodeId.Equals(input.EncodeId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.EncodeId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
