/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 予約成功応答データ
    /// </summary>
    [DataContract(Name = "AddedReserve")]
    public partial class AddedReserve : IEquatable<AddedReserve>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddedReserve" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddedReserve() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddedReserve" /> class.
        /// </summary>
        /// <param name="reserveId">予約 id (required).</param>
        public AddedReserve(int reserveId = default(int))
        {
            this.ReserveId = reserveId;
        }

        /// <summary>
        /// 予約 id
        /// </summary>
        /// <value>予約 id</value>
        [DataMember(Name = "reserveId", IsRequired = true, EmitDefaultValue = false)]
        public int ReserveId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddedReserve {\n");
            sb.Append("  ReserveId: ").Append(ReserveId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddedReserve);
        }

        /// <summary>
        /// Returns true if AddedReserve instances are equal
        /// </summary>
        /// <param name="input">Instance of AddedReserve to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddedReserve input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ReserveId == input.ReserveId ||
                    this.ReserveId.Equals(input.ReserveId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ReserveId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
