/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 録画番組情報の新規作成成功応答データ
    /// </summary>
    [DataContract(Name = "CreatedNewRecorded")]
    public partial class CreatedNewRecorded : IEquatable<CreatedNewRecorded>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatedNewRecorded" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatedNewRecorded() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatedNewRecorded" /> class.
        /// </summary>
        /// <param name="recordedId">録画済み番組 id (required).</param>
        public CreatedNewRecorded(int recordedId = default(int))
        {
            this.RecordedId = recordedId;
        }

        /// <summary>
        /// 録画済み番組 id
        /// </summary>
        /// <value>録画済み番組 id</value>
        [DataMember(Name = "recordedId", IsRequired = true, EmitDefaultValue = false)]
        public int RecordedId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatedNewRecorded {\n");
            sb.Append("  RecordedId: ").Append(RecordedId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreatedNewRecorded);
        }

        /// <summary>
        /// Returns true if CreatedNewRecorded instances are equal
        /// </summary>
        /// <param name="input">Instance of CreatedNewRecorded to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreatedNewRecorded input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RecordedId == input.RecordedId ||
                    this.RecordedId.Equals(input.RecordedId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.RecordedId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
