/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// ドロップログファイル情報
    /// </summary>
    [DataContract(Name = "DropLogFile")]
    public partial class DropLogFile : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DropLogFile" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DropLogFile() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DropLogFile" /> class.
        /// </summary>
        /// <param name="id">ドロップログファイル id (required).</param>
        /// <param name="errorCnt">エラーカウント (required).</param>
        /// <param name="dropCnt">ドロップカウント (required).</param>
        /// <param name="scramblingCnt">スクランブルカウント (required).</param>
        public DropLogFile(int id = default, int errorCnt = default, int dropCnt = default, int scramblingCnt = default)
        {
            this.Id = id;
            this.ErrorCnt = errorCnt;
            this.DropCnt = dropCnt;
            this.ScramblingCnt = scramblingCnt;
        }

        /// <summary>
        /// ドロップログファイル id
        /// </summary>
        /// <value>ドロップログファイル id</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// エラーカウント
        /// </summary>
        /// <value>エラーカウント</value>
        [DataMember(Name = "errorCnt", IsRequired = true, EmitDefaultValue = true)]
        public int ErrorCnt { get; set; }

        /// <summary>
        /// ドロップカウント
        /// </summary>
        /// <value>ドロップカウント</value>
        [DataMember(Name = "dropCnt", IsRequired = true, EmitDefaultValue = true)]
        public int DropCnt { get; set; }

        /// <summary>
        /// スクランブルカウント
        /// </summary>
        /// <value>スクランブルカウント</value>
        [DataMember(Name = "scramblingCnt", IsRequired = true, EmitDefaultValue = true)]
        public int ScramblingCnt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DropLogFile {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ErrorCnt: ").Append(ErrorCnt).Append("\n");
            sb.Append("  DropCnt: ").Append(DropCnt).Append("\n");
            sb.Append("  ScramblingCnt: ").Append(ScramblingCnt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
