/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// エンコード情報
    /// </summary>
    [DataContract(Name = "EncodeInfo")]
    public partial class EncodeInfo : IEquatable<EncodeInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EncodeInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EncodeInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EncodeInfo" /> class.
        /// </summary>
        /// <param name="runningItems">runningItems (required).</param>
        /// <param name="waitItems">waitItems (required).</param>
        public EncodeInfo(List<EncodeProgramItem> runningItems = default(List<EncodeProgramItem>), List<EncodeProgramItem> waitItems = default(List<EncodeProgramItem>))
        {
            // to ensure "runningItems" is required (not null)
            if (runningItems == null)
            {
                throw new ArgumentNullException("runningItems is a required property for EncodeInfo and cannot be null");
            }
            this.RunningItems = runningItems;
            // to ensure "waitItems" is required (not null)
            if (waitItems == null)
            {
                throw new ArgumentNullException("waitItems is a required property for EncodeInfo and cannot be null");
            }
            this.WaitItems = waitItems;
        }

        /// <summary>
        /// Gets or Sets RunningItems
        /// </summary>
        [DataMember(Name = "runningItems", IsRequired = true, EmitDefaultValue = false)]
        public List<EncodeProgramItem> RunningItems { get; set; }

        /// <summary>
        /// Gets or Sets WaitItems
        /// </summary>
        [DataMember(Name = "waitItems", IsRequired = true, EmitDefaultValue = false)]
        public List<EncodeProgramItem> WaitItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EncodeInfo {\n");
            sb.Append("  RunningItems: ").Append(RunningItems).Append("\n");
            sb.Append("  WaitItems: ").Append(WaitItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EncodeInfo);
        }

        /// <summary>
        /// Returns true if EncodeInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of EncodeInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EncodeInfo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RunningItems == input.RunningItems ||
                    this.RunningItems != null &&
                    input.RunningItems != null &&
                    this.RunningItems.SequenceEqual(input.RunningItems)
                ) && 
                (
                    this.WaitItems == input.WaitItems ||
                    this.WaitItems != null &&
                    input.WaitItems != null &&
                    this.WaitItems.SequenceEqual(input.WaitItems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RunningItems != null)
                {
                    hashCode = (hashCode * 59) + this.RunningItems.GetHashCode();
                }
                if (this.WaitItems != null)
                {
                    hashCode = (hashCode * 59) + this.WaitItems.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
