/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 番組ビデオ解像度
    /// </summary>
    /// <value>番組ビデオ解像度</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProgramVideoResolution
    {
        /// <summary>
        /// Enum _240p for value: 240p
        /// </summary>
        [EnumMember(Value = "240p")]
        _240p = 1,

        /// <summary>
        /// Enum _480i for value: 480i
        /// </summary>
        [EnumMember(Value = "480i")]
        _480i = 2,

        /// <summary>
        /// Enum _480p for value: 480p
        /// </summary>
        [EnumMember(Value = "480p")]
        _480p = 3,

        /// <summary>
        /// Enum _720p for value: 720p
        /// </summary>
        [EnumMember(Value = "720p")]
        _720p = 4,

        /// <summary>
        /// Enum _1080i for value: 1080i
        /// </summary>
        [EnumMember(Value = "1080i")]
        _1080i = 5,

        /// <summary>
        /// Enum _1080p for value: 1080p
        /// </summary>
        [EnumMember(Value = "1080p")]
        _1080p = 6,

        /// <summary>
        /// Enum _2160p for value: 2160p
        /// </summary>
        [EnumMember(Value = "2160p")]
        _2160p = 7,

        /// <summary>
        /// Enum _4320p for value: 4320p
        /// </summary>
        [EnumMember(Value = "4320p")]
        _4320p = 8
    }

}
