/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// recorded が持つ検索オプション情報
    /// </summary>
    [DataContract(Name = "RecordedSearchOptions")]
    public partial class RecordedSearchOptions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordedSearchOptions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecordedSearchOptions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordedSearchOptions" /> class.
        /// </summary>
        /// <param name="channels">channels (required).</param>
        /// <param name="genres">genres (required).</param>
        public RecordedSearchOptions(List<RecordedChannelListItem> channels = default, List<RecordedGenreListItem> genres = default)
        {
            // to ensure "channels" is required (not null)
            if (channels == null)
            {
                throw new ArgumentNullException("channels is a required property for RecordedSearchOptions and cannot be null");
            }
            this.Channels = channels;
            // to ensure "genres" is required (not null)
            if (genres == null)
            {
                throw new ArgumentNullException("genres is a required property for RecordedSearchOptions and cannot be null");
            }
            this.Genres = genres;
        }

        /// <summary>
        /// Gets or Sets Channels
        /// </summary>
        [DataMember(Name = "channels", IsRequired = true, EmitDefaultValue = true)]
        public List<RecordedChannelListItem> Channels { get; set; }

        /// <summary>
        /// Gets or Sets Genres
        /// </summary>
        [DataMember(Name = "genres", IsRequired = true, EmitDefaultValue = true)]
        public List<RecordedGenreListItem> Genres { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecordedSearchOptions {\n");
            sb.Append("  Channels: ").Append(Channels).Append("\n");
            sb.Append("  Genres: ").Append(Genres).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
