/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 録画情報
    /// </summary>
    [DataContract(Name = "Records")]
    public partial class Records : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Records" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Records() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Records" /> class.
        /// </summary>
        /// <param name="varRecords">varRecords (required).</param>
        /// <param name="total">録画総件数 (required).</param>
        public Records(List<RecordedItem> varRecords = default, int total = default)
        {
            // to ensure "varRecords" is required (not null)
            if (varRecords == null)
            {
                throw new ArgumentNullException("varRecords is a required property for Records and cannot be null");
            }
            this.VarRecords = varRecords;
            this.Total = total;
        }

        /// <summary>
        /// Gets or Sets VarRecords
        /// </summary>
        [DataMember(Name = "records", IsRequired = true, EmitDefaultValue = true)]
        public List<RecordedItem> VarRecords { get; set; }

        /// <summary>
        /// 録画総件数
        /// </summary>
        /// <value>録画総件数</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Records {\n");
            sb.Append("  VarRecords: ").Append(VarRecords).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
