/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// recorded が持つ genre のリスト
    /// </summary>
    [DataContract(Name = "RecordedGenreListItem")]
    public partial class RecordedGenreListItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordedGenreListItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecordedGenreListItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordedGenreListItem" /> class.
        /// </summary>
        /// <param name="cnt">録画数 (required).</param>
        /// <param name="genre">ジャンル (required).</param>
        public RecordedGenreListItem(int cnt = default, int genre = default)
        {
            this.Cnt = cnt;
            this.Genre = genre;
        }

        /// <summary>
        /// 録画数
        /// </summary>
        /// <value>録画数</value>
        [DataMember(Name = "cnt", IsRequired = true, EmitDefaultValue = true)]
        public int Cnt { get; set; }

        /// <summary>
        /// ジャンル
        /// </summary>
        /// <value>ジャンル</value>
        [DataMember(Name = "genre", IsRequired = true, EmitDefaultValue = true)]
        public int Genre { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecordedGenreListItem {\n");
            sb.Append("  Cnt: ").Append(Cnt).Append("\n");
            sb.Append("  Genre: ").Append(Genre).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
