/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 予約情報
    /// </summary>
    [DataContract(Name = "Reserves")]
    public partial class Reserves : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Reserves" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Reserves() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Reserves" /> class.
        /// </summary>
        /// <param name="varReserves">varReserves (required).</param>
        /// <param name="total">予約総件数 (required).</param>
        public Reserves(List<ReserveItem> varReserves = default(List<ReserveItem>), int total = default(int))
        {
            // to ensure "varReserves" is required (not null)
            if (varReserves == null)
            {
                throw new ArgumentNullException("varReserves is a required property for Reserves and cannot be null");
            }
            this.VarReserves = varReserves;
            this.Total = total;
        }

        /// <summary>
        /// Gets or Sets VarReserves
        /// </summary>
        [DataMember(Name = "reserves", IsRequired = true, EmitDefaultValue = true)]
        public List<ReserveItem> VarReserves { get; set; }

        /// <summary>
        /// 予約総件数
        /// </summary>
        /// <value>予約総件数</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Reserves {\n");
            sb.Append("  VarReserves: ").Append(VarReserves).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
