/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 予約情報
    /// </summary>
    [DataContract(Name = "Reserves")]
    public partial class Reserves : IEquatable<Reserves>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Reserves" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Reserves() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Reserves" /> class.
        /// </summary>
        /// <param name="reserves">reserves (required).</param>
        /// <param name="total">予約総件数 (required).</param>
        public Reserves(List<ReserveItem> reserves = default(List<ReserveItem>), int total = default(int))
        {
            // to ensure "reserves" is required (not null)
            if (reserves == null)
            {
                throw new ArgumentNullException("reserves is a required property for Reserves and cannot be null");
            }
            this._Reserves = reserves;
            this.Total = total;
        }

        /// <summary>
        /// Gets or Sets _Reserves
        /// </summary>
        [DataMember(Name = "reserves", IsRequired = true, EmitDefaultValue = false)]
        public List<ReserveItem> _Reserves { get; set; }

        /// <summary>
        /// 予約総件数
        /// </summary>
        /// <value>予約総件数</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = false)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Reserves {\n");
            sb.Append("  _Reserves: ").Append(_Reserves).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Reserves);
        }

        /// <summary>
        /// Returns true if Reserves instances are equal
        /// </summary>
        /// <param name="input">Instance of Reserves to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Reserves input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this._Reserves == input._Reserves ||
                    this._Reserves != null &&
                    input._Reserves != null &&
                    this._Reserves.SequenceEqual(input._Reserves)
                ) && 
                (
                    this.Total == input.Total ||
                    this.Total.Equals(input.Total)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Reserves != null)
                {
                    hashCode = (hashCode * 59) + this._Reserves.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Total.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
