/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 予約カウント
    /// </summary>
    [DataContract(Name = "ReserveCnts")]
    public partial class ReserveCnts : IEquatable<ReserveCnts>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReserveCnts" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReserveCnts() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReserveCnts" /> class.
        /// </summary>
        /// <param name="normal">通常予約数 (required).</param>
        /// <param name="conflicts">競合予約数 (required).</param>
        /// <param name="skips">競合予約数 (required).</param>
        /// <param name="overlaps">重複予約数 (required).</param>
        public ReserveCnts(int normal = default(int), int conflicts = default(int), int skips = default(int), int overlaps = default(int))
        {
            this.Normal = normal;
            this.Conflicts = conflicts;
            this.Skips = skips;
            this.Overlaps = overlaps;
        }

        /// <summary>
        /// 通常予約数
        /// </summary>
        /// <value>通常予約数</value>
        [DataMember(Name = "normal", IsRequired = true, EmitDefaultValue = false)]
        public int Normal { get; set; }

        /// <summary>
        /// 競合予約数
        /// </summary>
        /// <value>競合予約数</value>
        [DataMember(Name = "conflicts", IsRequired = true, EmitDefaultValue = false)]
        public int Conflicts { get; set; }

        /// <summary>
        /// 競合予約数
        /// </summary>
        /// <value>競合予約数</value>
        [DataMember(Name = "skips", IsRequired = true, EmitDefaultValue = false)]
        public int Skips { get; set; }

        /// <summary>
        /// 重複予約数
        /// </summary>
        /// <value>重複予約数</value>
        [DataMember(Name = "overlaps", IsRequired = true, EmitDefaultValue = false)]
        public int Overlaps { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReserveCnts {\n");
            sb.Append("  Normal: ").Append(Normal).Append("\n");
            sb.Append("  Conflicts: ").Append(Conflicts).Append("\n");
            sb.Append("  Skips: ").Append(Skips).Append("\n");
            sb.Append("  Overlaps: ").Append(Overlaps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReserveCnts);
        }

        /// <summary>
        /// Returns true if ReserveCnts instances are equal
        /// </summary>
        /// <param name="input">Instance of ReserveCnts to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReserveCnts input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Normal == input.Normal ||
                    this.Normal.Equals(input.Normal)
                ) && 
                (
                    this.Conflicts == input.Conflicts ||
                    this.Conflicts.Equals(input.Conflicts)
                ) && 
                (
                    this.Skips == input.Skips ||
                    this.Skips.Equals(input.Skips)
                ) && 
                (
                    this.Overlaps == input.Overlaps ||
                    this.Overlaps.Equals(input.Overlaps)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Normal.GetHashCode();
                hashCode = (hashCode * 59) + this.Conflicts.GetHashCode();
                hashCode = (hashCode * 59) + this.Skips.GetHashCode();
                hashCode = (hashCode * 59) + this.Overlaps.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
