/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// ルール情報
    /// </summary>
    [DataContract(Name = "Rules")]
    public partial class Rules : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rules" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Rules() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Rules" /> class.
        /// </summary>
        /// <param name="varRules">varRules (required).</param>
        /// <param name="total">ルール総件数 (required).</param>
        public Rules(List<Rule> varRules = default, int total = default)
        {
            // to ensure "varRules" is required (not null)
            if (varRules == null)
            {
                throw new ArgumentNullException("varRules is a required property for Rules and cannot be null");
            }
            this.VarRules = varRules;
            this.Total = total;
        }

        /// <summary>
        /// Gets or Sets VarRules
        /// </summary>
        [DataMember(Name = "rules", IsRequired = true, EmitDefaultValue = true)]
        public List<Rule> VarRules { get; set; }

        /// <summary>
        /// ルール総件数
        /// </summary>
        /// <value>ルール総件数</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rules {\n");
            sb.Append("  VarRules: ").Append(VarRules).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
