/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// 番組検索オプション
    /// </summary>
    [DataContract(Name = "ScheduleSearchOption")]
    public partial class ScheduleSearchOption : IEquatable<ScheduleSearchOption>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleSearchOption" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduleSearchOption() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleSearchOption" /> class.
        /// </summary>
        /// <param name="option">option (required).</param>
        /// <param name="isHalfWidth">半角文字で取得するか (required).</param>
        /// <param name="limit">検索結果取得最大件数.</param>
        public ScheduleSearchOption(RuleSearchOption option = default(RuleSearchOption), bool isHalfWidth = default(bool), decimal limit = default(decimal))
        {
            // to ensure "option" is required (not null)
            if (option == null)
            {
                throw new ArgumentNullException("option is a required property for ScheduleSearchOption and cannot be null");
            }
            this.Option = option;
            this.IsHalfWidth = isHalfWidth;
            this.Limit = limit;
        }

        /// <summary>
        /// Gets or Sets Option
        /// </summary>
        [DataMember(Name = "option", IsRequired = true, EmitDefaultValue = false)]
        public RuleSearchOption Option { get; set; }

        /// <summary>
        /// 半角文字で取得するか
        /// </summary>
        /// <value>半角文字で取得するか</value>
        [DataMember(Name = "isHalfWidth", IsRequired = true, EmitDefaultValue = true)]
        public bool IsHalfWidth { get; set; }

        /// <summary>
        /// 検索結果取得最大件数
        /// </summary>
        /// <value>検索結果取得最大件数</value>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScheduleSearchOption {\n");
            sb.Append("  Option: ").Append(Option).Append("\n");
            sb.Append("  IsHalfWidth: ").Append(IsHalfWidth).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduleSearchOption);
        }

        /// <summary>
        /// Returns true if ScheduleSearchOption instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduleSearchOption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduleSearchOption input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Option == input.Option ||
                    (this.Option != null &&
                    this.Option.Equals(input.Option))
                ) && 
                (
                    this.IsHalfWidth == input.IsHalfWidth ||
                    this.IsHalfWidth.Equals(input.IsHalfWidth)
                ) && 
                (
                    this.Limit == input.Limit ||
                    this.Limit.Equals(input.Limit)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Option != null)
                {
                    hashCode = (hashCode * 59) + this.Option.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsHalfWidth.GetHashCode();
                hashCode = (hashCode * 59) + this.Limit.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
