/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// kodiへビデオリンクを送信するときのオプション
    /// </summary>
    [DataContract(Name = "SendVideoLinkToKodiOption")]
    public partial class SendVideoLinkToKodiOption : IEquatable<SendVideoLinkToKodiOption>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendVideoLinkToKodiOption" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendVideoLinkToKodiOption() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendVideoLinkToKodiOption" /> class.
        /// </summary>
        /// <param name="kodiName">config の kodi の name (required).</param>
        public SendVideoLinkToKodiOption(string kodiName = default(string))
        {
            // to ensure "kodiName" is required (not null)
            if (kodiName == null)
            {
                throw new ArgumentNullException("kodiName is a required property for SendVideoLinkToKodiOption and cannot be null");
            }
            this.KodiName = kodiName;
        }

        /// <summary>
        /// config の kodi の name
        /// </summary>
        /// <value>config の kodi の name</value>
        [DataMember(Name = "kodiName", IsRequired = true, EmitDefaultValue = false)]
        public string KodiName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendVideoLinkToKodiOption {\n");
            sb.Append("  KodiName: ").Append(KodiName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SendVideoLinkToKodiOption);
        }

        /// <summary>
        /// Returns true if SendVideoLinkToKodiOption instances are equal
        /// </summary>
        /// <param name="input">Instance of SendVideoLinkToKodiOption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SendVideoLinkToKodiOption input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.KodiName == input.KodiName ||
                    (this.KodiName != null &&
                    this.KodiName.Equals(input.KodiName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.KodiName != null)
                {
                    hashCode = (hashCode * 59) + this.KodiName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
