/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// ストリームの種類
    /// </summary>
    /// <value>ストリームの種類</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum StreamType
    {
        /// <summary>
        /// Enum LiveStream for value: LiveStream
        /// </summary>
        [EnumMember(Value = "LiveStream")]
        LiveStream = 1,

        /// <summary>
        /// Enum LiveHLS for value: LiveHLS
        /// </summary>
        [EnumMember(Value = "LiveHLS")]
        LiveHLS = 2,

        /// <summary>
        /// Enum RecordedStream for value: RecordedStream
        /// </summary>
        [EnumMember(Value = "RecordedStream")]
        RecordedStream = 3,

        /// <summary>
        /// Enum RecordedHLS for value: RecordedHLS
        /// </summary>
        [EnumMember(Value = "RecordedHLS")]
        RecordedHLS = 4

    }

}
