/*
 * epgstation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.6.20
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = X68fpjc.Jellyfin.EPGStation.OpenAPI.Client.OpenAPIDateConverter;

namespace X68fpjc.Jellyfin.EPGStation.OpenAPI.Model
{
    /// <summary>
    /// ビデオファイル情報
    /// </summary>
    [DataContract(Name = "VideoFile")]
    public partial class VideoFile : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public VideoFileType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoFile" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VideoFile() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoFile" /> class.
        /// </summary>
        /// <param name="id">ビデオファイル id (required).</param>
        /// <param name="name">ビデオ名 (Web上の表示名) (required).</param>
        /// <param name="filename">ビデオファイル名.</param>
        /// <param name="type">type (required).</param>
        /// <param name="size">ファイルサイズ (required).</param>
        public VideoFile(int id = default(int), string name = default(string), string filename = default(string), VideoFileType type = default(VideoFileType), long size = default(long))
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for VideoFile and cannot be null");
            }
            this.Name = name;
            this.Type = type;
            this.Size = size;
            this.Filename = filename;
        }

        /// <summary>
        /// ビデオファイル id
        /// </summary>
        /// <value>ビデオファイル id</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// ビデオ名 (Web上の表示名)
        /// </summary>
        /// <value>ビデオ名 (Web上の表示名)</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// ビデオファイル名
        /// </summary>
        /// <value>ビデオファイル名</value>
        [DataMember(Name = "filename", EmitDefaultValue = false)]
        public string Filename { get; set; }

        /// <summary>
        /// ファイルサイズ
        /// </summary>
        /// <value>ファイルサイズ</value>
        [DataMember(Name = "size", IsRequired = true, EmitDefaultValue = true)]
        public long Size { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VideoFile {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
